/**
 * API Banco del Cisne
 * API REST para el sistema bancario del Cisne
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@bancodelcisne.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ClienteResponseDTO { 
    idCliente?: number;
    cedula?: string;
    nombres?: string;
    apellidos?: string;
    email?: string;
    telefono?: string;
    direccion?: string;
    fechaNacimiento?: string;
    estado?: ClienteResponseDTO.EstadoEnum;
    fechaRegistro?: Date;
}
export namespace ClienteResponseDTO {
    export type EstadoEnum = 'ACTIVO' | 'INACTIVO' | 'BLOQUEADO' | 'SUSPENDIDO';
    export const EstadoEnum = {
        ACTIVO: 'ACTIVO' as EstadoEnum,
        INACTIVO: 'INACTIVO' as EstadoEnum,
        BLOQUEADO: 'BLOQUEADO' as EstadoEnum,
        SUSPENDIDO: 'SUSPENDIDO' as EstadoEnum
    };
}