export * from './autenticacin.service';
import { AutenticacinService } from './autenticacin.service';
export * from './clienteController.service';
import { ClienteControllerService } from './clienteController.service';
export * from './cuentasDeAhorro.service';
import { CuentasDeAhorroService } from './cuentasDeAhorro.service';
export * from './pagosDePrstamos.service';
import { PagosDePrstamosService } from './pagosDePrstamos.service';
export * from './prstamos.service';
import { PrstamosService } from './prstamos.service';
export * from './transaccionesDeAhorro.service';
import { TransaccionesDeAhorroService } from './transaccionesDeAhorro.service';
export const APIS = [AutenticacinService, ClienteControllerService, CuentasDeAhorroService, PagosDePrstamosService, PrstamosService, TransaccionesDeAhorroService];
