/**
 * API Banco del Cisne
 * API REST para el sistema bancario del Cisne
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@bancodelcisne.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CuentaAhorroRequestDTO } from '../model/cuentaAhorroRequestDTO';
import { CuentaAhorroResponseDTO } from '../model/cuentaAhorroResponseDTO';
import { TransaccionAhorroRequestDTO } from '../model/transaccionAhorroRequestDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class CuentasDeAhorroService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Activar cuenta
     * Cambia el estado de la cuenta a activo
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public activarCuenta(id: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public activarCuenta(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public activarCuenta(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public activarCuenta(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling activarCuenta.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('patch',`${this.basePath}/api/cuentas-ahorro/${encodeURIComponent(String(id))}/activar`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Actualizar cuenta
     * Actualiza los datos de una cuenta de ahorro existente
     * @param body 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public actualizarCuenta(body: CuentaAhorroRequestDTO, id: number, observe?: 'body', reportProgress?: boolean): Observable<CuentaAhorroResponseDTO>;
    public actualizarCuenta(body: CuentaAhorroRequestDTO, id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CuentaAhorroResponseDTO>>;
    public actualizarCuenta(body: CuentaAhorroRequestDTO, id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CuentaAhorroResponseDTO>>;
    public actualizarCuenta(body: CuentaAhorroRequestDTO, id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling actualizarCuenta.');
        }

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling actualizarCuenta.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<CuentaAhorroResponseDTO>('put',`${this.basePath}/api/cuentas-ahorro/${encodeURIComponent(String(id))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Actualizar saldo
     * Actualiza el saldo de una cuenta de ahorro
     * @param id 
     * @param nuevoSaldo 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public actualizarSaldo(id: number, nuevoSaldo: number, observe?: 'body', reportProgress?: boolean): Observable<CuentaAhorroResponseDTO>;
    public actualizarSaldo(id: number, nuevoSaldo: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CuentaAhorroResponseDTO>>;
    public actualizarSaldo(id: number, nuevoSaldo: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CuentaAhorroResponseDTO>>;
    public actualizarSaldo(id: number, nuevoSaldo: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling actualizarSaldo.');
        }

        if (nuevoSaldo === null || nuevoSaldo === undefined) {
            throw new Error('Required parameter nuevoSaldo was null or undefined when calling actualizarSaldo.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (nuevoSaldo !== undefined && nuevoSaldo !== null) {
            queryParameters = queryParameters.set('nuevoSaldo', <any>nuevoSaldo);
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<CuentaAhorroResponseDTO>('patch',`${this.basePath}/api/cuentas-ahorro/${encodeURIComponent(String(id))}/saldo`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Crear nueva cuenta de ahorro
     * Registra una nueva cuenta de ahorro para un cliente
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public crearCuenta(body: CuentaAhorroRequestDTO, observe?: 'body', reportProgress?: boolean): Observable<CuentaAhorroResponseDTO>;
    public crearCuenta(body: CuentaAhorroRequestDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CuentaAhorroResponseDTO>>;
    public crearCuenta(body: CuentaAhorroRequestDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CuentaAhorroResponseDTO>>;
    public crearCuenta(body: CuentaAhorroRequestDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling crearCuenta.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<CuentaAhorroResponseDTO>('post',`${this.basePath}/api/cuentas-ahorro/crearCuenta`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Desactivar cuenta
     * Cambia el estado de la cuenta a inactivo
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public desactivarCuenta(id: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public desactivarCuenta(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public desactivarCuenta(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public desactivarCuenta(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling desactivarCuenta.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('patch',`${this.basePath}/api/cuentas-ahorro/${encodeURIComponent(String(id))}/desactivar`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtener cuenta por ID
     * Retorna una cuenta de ahorro por su ID
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerCuentaPorId(id: number, observe?: 'body', reportProgress?: boolean): Observable<CuentaAhorroResponseDTO>;
    public obtenerCuentaPorId(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CuentaAhorroResponseDTO>>;
    public obtenerCuentaPorId(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CuentaAhorroResponseDTO>>;
    public obtenerCuentaPorId(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling obtenerCuentaPorId.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<CuentaAhorroResponseDTO>('get',`${this.basePath}/api/cuentas-ahorro/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtener cuenta por número
     * Retorna una cuenta de ahorro por su número de cuenta
     * @param numeroCuenta 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerCuentaPorNumero(numeroCuenta: string, observe?: 'body', reportProgress?: boolean): Observable<CuentaAhorroResponseDTO>;
    public obtenerCuentaPorNumero(numeroCuenta: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CuentaAhorroResponseDTO>>;
    public obtenerCuentaPorNumero(numeroCuenta: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CuentaAhorroResponseDTO>>;
    public obtenerCuentaPorNumero(numeroCuenta: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (numeroCuenta === null || numeroCuenta === undefined) {
            throw new Error('Required parameter numeroCuenta was null or undefined when calling obtenerCuentaPorNumero.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<CuentaAhorroResponseDTO>('get',`${this.basePath}/api/cuentas-ahorro/numero/${encodeURIComponent(String(numeroCuenta))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtener cuentas por cliente
     * Retorna todas las cuentas de ahorro de un cliente
     * @param idCliente 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerCuentasPorCliente(idCliente: number, observe?: 'body', reportProgress?: boolean): Observable<Array<CuentaAhorroResponseDTO>>;
    public obtenerCuentasPorCliente(idCliente: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CuentaAhorroResponseDTO>>>;
    public obtenerCuentasPorCliente(idCliente: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CuentaAhorroResponseDTO>>>;
    public obtenerCuentasPorCliente(idCliente: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idCliente === null || idCliente === undefined) {
            throw new Error('Required parameter idCliente was null or undefined when calling obtenerCuentasPorCliente.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<CuentaAhorroResponseDTO>>('get',`${this.basePath}/api/cuentas-ahorro/cliente/${encodeURIComponent(String(idCliente))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Listar todas las cuentas
     * Retorna lista completa de cuentas de ahorro
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerTodasLasCuentas(observe?: 'body', reportProgress?: boolean): Observable<Array<CuentaAhorroResponseDTO>>;
    public obtenerTodasLasCuentas(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CuentaAhorroResponseDTO>>>;
    public obtenerTodasLasCuentas(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CuentaAhorroResponseDTO>>>;
    public obtenerTodasLasCuentas(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<CuentaAhorroResponseDTO>>('get',`${this.basePath}/api/cuentas-ahorro/listarCtaAhorro`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Realizar depósito
     * Registra un depósito en una cuenta de ahorro
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public realizarDeposito1(body: TransaccionAhorroRequestDTO, observe?: 'body', reportProgress?: boolean): Observable<CuentaAhorroResponseDTO>;
    public realizarDeposito1(body: TransaccionAhorroRequestDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CuentaAhorroResponseDTO>>;
    public realizarDeposito1(body: TransaccionAhorroRequestDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CuentaAhorroResponseDTO>>;
    public realizarDeposito1(body: TransaccionAhorroRequestDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling realizarDeposito1.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<CuentaAhorroResponseDTO>('post',`${this.basePath}/api/cuentas-ahorro/deposito`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Realizar retiro
     * Registra un retiro de una cuenta de ahorro
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public realizarRetiro1(body: TransaccionAhorroRequestDTO, observe?: 'body', reportProgress?: boolean): Observable<CuentaAhorroResponseDTO>;
    public realizarRetiro1(body: TransaccionAhorroRequestDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CuentaAhorroResponseDTO>>;
    public realizarRetiro1(body: TransaccionAhorroRequestDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CuentaAhorroResponseDTO>>;
    public realizarRetiro1(body: TransaccionAhorroRequestDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling realizarRetiro1.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<CuentaAhorroResponseDTO>('post',`${this.basePath}/api/cuentas-ahorro/retiro`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
