/**
 * API Banco del Cisne
 * API REST para el sistema bancario del Cisne
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@bancodelcisne.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AmortizacionDTO } from '../model/amortizacionDTO';
import { PagoPrestamoRequestDTO } from '../model/pagoPrestamoRequestDTO';
import { PagoPrestamoResponseDTO } from '../model/pagoPrestamoResponseDTO';
import { ResumenPagosPrestamoDTO } from '../model/resumenPagosPrestamoDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class PagosDePrstamosService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Obtener cuotas pagadas
     * Retorna las cuotas ya pagadas de un préstamo
     * @param idPrestamo 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerCuotasPagadas(idPrestamo: number, observe?: 'body', reportProgress?: boolean): Observable<Array<AmortizacionDTO>>;
    public obtenerCuotasPagadas(idPrestamo: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<AmortizacionDTO>>>;
    public obtenerCuotasPagadas(idPrestamo: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<AmortizacionDTO>>>;
    public obtenerCuotasPagadas(idPrestamo: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPrestamo === null || idPrestamo === undefined) {
            throw new Error('Required parameter idPrestamo was null or undefined when calling obtenerCuotasPagadas.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<AmortizacionDTO>>('get',`${this.basePath}/api/pagos-prestamos/prestamo/${encodeURIComponent(String(idPrestamo))}/cuotas-pagadas`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtener cuotas pendientes
     * Retorna las cuotas pendientes de pago de un préstamo
     * @param idPrestamo 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerCuotasPendientes(idPrestamo: number, observe?: 'body', reportProgress?: boolean): Observable<Array<AmortizacionDTO>>;
    public obtenerCuotasPendientes(idPrestamo: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<AmortizacionDTO>>>;
    public obtenerCuotasPendientes(idPrestamo: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<AmortizacionDTO>>>;
    public obtenerCuotasPendientes(idPrestamo: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPrestamo === null || idPrestamo === undefined) {
            throw new Error('Required parameter idPrestamo was null or undefined when calling obtenerCuotasPendientes.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<AmortizacionDTO>>('get',`${this.basePath}/api/pagos-prestamos/prestamo/${encodeURIComponent(String(idPrestamo))}/cuotas-pendientes`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtener pago por ID
     * Retorna un pago específico por su ID
     * @param idPago 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerPagoPorId(idPago: number, observe?: 'body', reportProgress?: boolean): Observable<PagoPrestamoResponseDTO>;
    public obtenerPagoPorId(idPago: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PagoPrestamoResponseDTO>>;
    public obtenerPagoPorId(idPago: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PagoPrestamoResponseDTO>>;
    public obtenerPagoPorId(idPago: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPago === null || idPago === undefined) {
            throw new Error('Required parameter idPago was null or undefined when calling obtenerPagoPorId.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<PagoPrestamoResponseDTO>('get',`${this.basePath}/api/pagos-prestamos/${encodeURIComponent(String(idPago))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtener pagos por cliente
     * Retorna todos los pagos realizados por un cliente en todos sus préstamos
     * @param idCliente 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerPagosPorCliente(idCliente: number, observe?: 'body', reportProgress?: boolean): Observable<Array<PagoPrestamoResponseDTO>>;
    public obtenerPagosPorCliente(idCliente: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PagoPrestamoResponseDTO>>>;
    public obtenerPagosPorCliente(idCliente: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PagoPrestamoResponseDTO>>>;
    public obtenerPagosPorCliente(idCliente: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idCliente === null || idCliente === undefined) {
            throw new Error('Required parameter idCliente was null or undefined when calling obtenerPagosPorCliente.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<PagoPrestamoResponseDTO>>('get',`${this.basePath}/api/pagos-prestamos/cliente/${encodeURIComponent(String(idCliente))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtener pagos de un préstamo
     * Retorna todos los pagos realizados de un préstamo específico, ordenados por número de cuota
     * @param idPrestamo 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerPagosPorPrestamo(idPrestamo: number, observe?: 'body', reportProgress?: boolean): Observable<Array<PagoPrestamoResponseDTO>>;
    public obtenerPagosPorPrestamo(idPrestamo: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PagoPrestamoResponseDTO>>>;
    public obtenerPagosPorPrestamo(idPrestamo: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PagoPrestamoResponseDTO>>>;
    public obtenerPagosPorPrestamo(idPrestamo: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPrestamo === null || idPrestamo === undefined) {
            throw new Error('Required parameter idPrestamo was null or undefined when calling obtenerPagosPorPrestamo.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<PagoPrestamoResponseDTO>>('get',`${this.basePath}/api/pagos-prestamos/prestamo/${encodeURIComponent(String(idPrestamo))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtener próxima cuota a vencer
     * Retorna la próxima cuota pendiente de pago de un préstamo
     * @param idPrestamo 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerProximaCuotaAVencer(idPrestamo: number, observe?: 'body', reportProgress?: boolean): Observable<AmortizacionDTO>;
    public obtenerProximaCuotaAVencer(idPrestamo: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AmortizacionDTO>>;
    public obtenerProximaCuotaAVencer(idPrestamo: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AmortizacionDTO>>;
    public obtenerProximaCuotaAVencer(idPrestamo: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPrestamo === null || idPrestamo === undefined) {
            throw new Error('Required parameter idPrestamo was null or undefined when calling obtenerProximaCuotaAVencer.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<AmortizacionDTO>('get',`${this.basePath}/api/pagos-prestamos/prestamo/${encodeURIComponent(String(idPrestamo))}/proxima-cuota`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtener resumen de pagos
     * Retorna un resumen completo de los pagos de un préstamo (cuotas pagadas, pendientes, totales, etc.)
     * @param idPrestamo 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerResumenPagos(idPrestamo: number, observe?: 'body', reportProgress?: boolean): Observable<ResumenPagosPrestamoDTO>;
    public obtenerResumenPagos(idPrestamo: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResumenPagosPrestamoDTO>>;
    public obtenerResumenPagos(idPrestamo: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResumenPagosPrestamoDTO>>;
    public obtenerResumenPagos(idPrestamo: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPrestamo === null || idPrestamo === undefined) {
            throw new Error('Required parameter idPrestamo was null or undefined when calling obtenerResumenPagos.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ResumenPagosPrestamoDTO>('get',`${this.basePath}/api/pagos-prestamos/prestamo/${encodeURIComponent(String(idPrestamo))}/resumen`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Listar todos los pagos
     * Retorna lista completa de todos los pagos realizados, ordenados por fecha descendente
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerTodosLosPagos(observe?: 'body', reportProgress?: boolean): Observable<Array<PagoPrestamoResponseDTO>>;
    public obtenerTodosLosPagos(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PagoPrestamoResponseDTO>>>;
    public obtenerTodosLosPagos(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PagoPrestamoResponseDTO>>>;
    public obtenerTodosLosPagos(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<PagoPrestamoResponseDTO>>('get',`${this.basePath}/api/pagos-prestamos`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Registrar pago de préstamo
     * Registra el pago de una cuota del préstamo
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public registrarPago(body: PagoPrestamoRequestDTO, observe?: 'body', reportProgress?: boolean): Observable<PagoPrestamoResponseDTO>;
    public registrarPago(body: PagoPrestamoRequestDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PagoPrestamoResponseDTO>>;
    public registrarPago(body: PagoPrestamoRequestDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PagoPrestamoResponseDTO>>;
    public registrarPago(body: PagoPrestamoRequestDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling registrarPago.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<PagoPrestamoResponseDTO>('post',`${this.basePath}/api/pagos-prestamos`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
