/**
 * API Banco del Cisne
 * API REST para el sistema bancario del Cisne
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@bancodelcisne.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ActualizarPlazoPrestamoDTO } from '../model/actualizarPlazoPrestamoDTO';
import { AmortizacionDTO } from '../model/amortizacionDTO';
import { AprobarPrestamoDTO } from '../model/aprobarPrestamoDTO';
import { CalcularCuotaRequestDTO } from '../model/calcularCuotaRequestDTO';
import { CalcularCuotaResponseDTO } from '../model/calcularCuotaResponseDTO';
import { PrestamoRequestDTO } from '../model/prestamoRequestDTO';
import { PrestamoResponseDTO } from '../model/prestamoResponseDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class PrstamosService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Actualizar plazo del préstamo
     * Actualiza el plazo en meses de un préstamo y recalcula la cuota mensual y la tabla de amortización. Solo permite cambios en préstamos SOLICITADOS o APROBADOS sin pagos realizados.
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public actualizarPlazoPrestamo(body: ActualizarPlazoPrestamoDTO, observe?: 'body', reportProgress?: boolean): Observable<PrestamoResponseDTO>;
    public actualizarPlazoPrestamo(body: ActualizarPlazoPrestamoDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PrestamoResponseDTO>>;
    public actualizarPlazoPrestamo(body: ActualizarPlazoPrestamoDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PrestamoResponseDTO>>;
    public actualizarPlazoPrestamo(body: ActualizarPlazoPrestamoDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling actualizarPlazoPrestamo.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<PrestamoResponseDTO>('put',`${this.basePath}/api/prestamos/actualizar-plazo`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Aprobar préstamo
     * Aprueba un préstamo pendiente y genera la tabla de amortización
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public aprobarPrestamo(body: AprobarPrestamoDTO, observe?: 'body', reportProgress?: boolean): Observable<PrestamoResponseDTO>;
    public aprobarPrestamo(body: AprobarPrestamoDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PrestamoResponseDTO>>;
    public aprobarPrestamo(body: AprobarPrestamoDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PrestamoResponseDTO>>;
    public aprobarPrestamo(body: AprobarPrestamoDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling aprobarPrestamo.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<PrestamoResponseDTO>('post',`${this.basePath}/api/prestamos/aprobar`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Calcular cuota mensual
     * Calcula la cuota mensual de un préstamo sin crear la solicitud. Útil para que el cliente conozca su cuota antes de solicitar el préstamo. Aplica 1% de interés mensual fijo.
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public calcularCuotaMensual(body: CalcularCuotaRequestDTO, observe?: 'body', reportProgress?: boolean): Observable<CalcularCuotaResponseDTO>;
    public calcularCuotaMensual(body: CalcularCuotaRequestDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CalcularCuotaResponseDTO>>;
    public calcularCuotaMensual(body: CalcularCuotaRequestDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CalcularCuotaResponseDTO>>;
    public calcularCuotaMensual(body: CalcularCuotaRequestDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling calcularCuotaMensual.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<CalcularCuotaResponseDTO>('post',`${this.basePath}/api/prestamos/calcular-cuota`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtener préstamo por ID
     * Retorna un préstamo por su ID
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerPrestamoPorId(id: number, observe?: 'body', reportProgress?: boolean): Observable<PrestamoResponseDTO>;
    public obtenerPrestamoPorId(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PrestamoResponseDTO>>;
    public obtenerPrestamoPorId(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PrestamoResponseDTO>>;
    public obtenerPrestamoPorId(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling obtenerPrestamoPorId.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<PrestamoResponseDTO>('get',`${this.basePath}/api/prestamos/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtener préstamos por cliente
     * Retorna todos los préstamos de un cliente
     * @param idCliente 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerPrestamosPorCliente(idCliente: number, observe?: 'body', reportProgress?: boolean): Observable<Array<PrestamoResponseDTO>>;
    public obtenerPrestamosPorCliente(idCliente: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PrestamoResponseDTO>>>;
    public obtenerPrestamosPorCliente(idCliente: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PrestamoResponseDTO>>>;
    public obtenerPrestamosPorCliente(idCliente: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idCliente === null || idCliente === undefined) {
            throw new Error('Required parameter idCliente was null or undefined when calling obtenerPrestamosPorCliente.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<PrestamoResponseDTO>>('get',`${this.basePath}/api/prestamos/cliente/${encodeURIComponent(String(idCliente))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtener préstamos por estado
     * Retorna préstamos filtrados por estado
     * @param estado 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerPrestamosPorEstado(estado: string, observe?: 'body', reportProgress?: boolean): Observable<Array<PrestamoResponseDTO>>;
    public obtenerPrestamosPorEstado(estado: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PrestamoResponseDTO>>>;
    public obtenerPrestamosPorEstado(estado: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PrestamoResponseDTO>>>;
    public obtenerPrestamosPorEstado(estado: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (estado === null || estado === undefined) {
            throw new Error('Required parameter estado was null or undefined when calling obtenerPrestamosPorEstado.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<PrestamoResponseDTO>>('get',`${this.basePath}/api/prestamos/estado/${encodeURIComponent(String(estado))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtener tabla de amortización
     * Retorna la tabla de amortización de un préstamo
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerTablaAmortizacion(id: number, observe?: 'body', reportProgress?: boolean): Observable<Array<AmortizacionDTO>>;
    public obtenerTablaAmortizacion(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<AmortizacionDTO>>>;
    public obtenerTablaAmortizacion(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<AmortizacionDTO>>>;
    public obtenerTablaAmortizacion(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling obtenerTablaAmortizacion.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<AmortizacionDTO>>('get',`${this.basePath}/api/prestamos/${encodeURIComponent(String(id))}/amortizacion`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Listar todos los préstamos
     * Retorna lista completa de préstamos
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerTodosLosPrestamos(observe?: 'body', reportProgress?: boolean): Observable<Array<PrestamoResponseDTO>>;
    public obtenerTodosLosPrestamos(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PrestamoResponseDTO>>>;
    public obtenerTodosLosPrestamos(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PrestamoResponseDTO>>>;
    public obtenerTodosLosPrestamos(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<PrestamoResponseDTO>>('get',`${this.basePath}/api/prestamos`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Solicitar préstamo
     * Crea una nueva solicitud de préstamo
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public solicitarPrestamo(body: PrestamoRequestDTO, observe?: 'body', reportProgress?: boolean): Observable<PrestamoResponseDTO>;
    public solicitarPrestamo(body: PrestamoRequestDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PrestamoResponseDTO>>;
    public solicitarPrestamo(body: PrestamoRequestDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PrestamoResponseDTO>>;
    public solicitarPrestamo(body: PrestamoRequestDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling solicitarPrestamo.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<PrestamoResponseDTO>('post',`${this.basePath}/api/prestamos/solicitar`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
