/**
 * API Banco del Cisne
 * API REST para el sistema bancario del Cisne
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@bancodelcisne.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { TransaccionAhorroRequestDTO } from '../model/transaccionAhorroRequestDTO';
import { TransaccionAhorroResponseDTO } from '../model/transaccionAhorroResponseDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class TransaccionesDeAhorroService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Generar intereses de cuenta
     * Genera y aplica intereses a una cuenta de ahorro basado en la fecha de corte
     * @param idCuenta 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public generarIntereses(idCuenta: number, observe?: 'body', reportProgress?: boolean): Observable<TransaccionAhorroResponseDTO>;
    public generarIntereses(idCuenta: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TransaccionAhorroResponseDTO>>;
    public generarIntereses(idCuenta: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TransaccionAhorroResponseDTO>>;
    public generarIntereses(idCuenta: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idCuenta === null || idCuenta === undefined) {
            throw new Error('Required parameter idCuenta was null or undefined when calling generarIntereses.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<TransaccionAhorroResponseDTO>('post',`${this.basePath}/api/transacciones-ahorro/generar-intereses/${encodeURIComponent(String(idCuenta))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Generar intereses para todas las cuentas
     * Genera intereses para todas las cuentas activas que cumplan con los requisitos
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public generarInteresesTodasLasCuentas(observe?: 'body', reportProgress?: boolean): Observable<string>;
    public generarInteresesTodasLasCuentas(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public generarInteresesTodasLasCuentas(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public generarInteresesTodasLasCuentas(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<string>('post',`${this.basePath}/api/transacciones-ahorro/generar-intereses-todas`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Listar todas las transacciones
     * Retorna lista completa de transacciones de ahorro
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerTodasLasTransacciones(observe?: 'body', reportProgress?: boolean): Observable<Array<TransaccionAhorroResponseDTO>>;
    public obtenerTodasLasTransacciones(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<TransaccionAhorroResponseDTO>>>;
    public obtenerTodasLasTransacciones(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<TransaccionAhorroResponseDTO>>>;
    public obtenerTodasLasTransacciones(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<TransaccionAhorroResponseDTO>>('get',`${this.basePath}/api/transacciones-ahorro`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtener transacción por ID
     * Retorna una transacción por su ID
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerTransaccionPorId(id: number, observe?: 'body', reportProgress?: boolean): Observable<TransaccionAhorroResponseDTO>;
    public obtenerTransaccionPorId(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TransaccionAhorroResponseDTO>>;
    public obtenerTransaccionPorId(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TransaccionAhorroResponseDTO>>;
    public obtenerTransaccionPorId(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling obtenerTransaccionPorId.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<TransaccionAhorroResponseDTO>('get',`${this.basePath}/api/transacciones-ahorro/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtener transacciones por cuenta
     * Retorna todas las transacciones de una cuenta de ahorro
     * @param idCuenta 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerTransaccionesPorCuenta(idCuenta: number, observe?: 'body', reportProgress?: boolean): Observable<Array<TransaccionAhorroResponseDTO>>;
    public obtenerTransaccionesPorCuenta(idCuenta: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<TransaccionAhorroResponseDTO>>>;
    public obtenerTransaccionesPorCuenta(idCuenta: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<TransaccionAhorroResponseDTO>>>;
    public obtenerTransaccionesPorCuenta(idCuenta: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idCuenta === null || idCuenta === undefined) {
            throw new Error('Required parameter idCuenta was null or undefined when calling obtenerTransaccionesPorCuenta.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<TransaccionAhorroResponseDTO>>('get',`${this.basePath}/api/transacciones-ahorro/cuenta/${encodeURIComponent(String(idCuenta))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtener transacciones por cuenta y fechas
     * Retorna transacciones de una cuenta en un rango de fechas
     * @param idCuenta 
     * @param fechaInicio 
     * @param fechaFin 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerTransaccionesPorCuentaYFechas(idCuenta: number, fechaInicio: string, fechaFin: string, observe?: 'body', reportProgress?: boolean): Observable<Array<TransaccionAhorroResponseDTO>>;
    public obtenerTransaccionesPorCuentaYFechas(idCuenta: number, fechaInicio: string, fechaFin: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<TransaccionAhorroResponseDTO>>>;
    public obtenerTransaccionesPorCuentaYFechas(idCuenta: number, fechaInicio: string, fechaFin: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<TransaccionAhorroResponseDTO>>>;
    public obtenerTransaccionesPorCuentaYFechas(idCuenta: number, fechaInicio: string, fechaFin: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idCuenta === null || idCuenta === undefined) {
            throw new Error('Required parameter idCuenta was null or undefined when calling obtenerTransaccionesPorCuentaYFechas.');
        }

        if (fechaInicio === null || fechaInicio === undefined) {
            throw new Error('Required parameter fechaInicio was null or undefined when calling obtenerTransaccionesPorCuentaYFechas.');
        }

        if (fechaFin === null || fechaFin === undefined) {
            throw new Error('Required parameter fechaFin was null or undefined when calling obtenerTransaccionesPorCuentaYFechas.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (fechaInicio !== undefined && fechaInicio !== null) {
            queryParameters = queryParameters.set('fechaInicio', <any>fechaInicio);
        }
        if (fechaFin !== undefined && fechaFin !== null) {
            queryParameters = queryParameters.set('fechaFin', <any>fechaFin);
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<TransaccionAhorroResponseDTO>>('get',`${this.basePath}/api/transacciones-ahorro/cuenta/${encodeURIComponent(String(idCuenta))}/fechas`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Realizar depósito
     * Registra un depósito en una cuenta de ahorro
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public realizarDeposito(body: TransaccionAhorroRequestDTO, observe?: 'body', reportProgress?: boolean): Observable<TransaccionAhorroResponseDTO>;
    public realizarDeposito(body: TransaccionAhorroRequestDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TransaccionAhorroResponseDTO>>;
    public realizarDeposito(body: TransaccionAhorroRequestDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TransaccionAhorroResponseDTO>>;
    public realizarDeposito(body: TransaccionAhorroRequestDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling realizarDeposito.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<TransaccionAhorroResponseDTO>('post',`${this.basePath}/api/transacciones-ahorro/deposito`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Realizar retiro
     * Registra un retiro de una cuenta de ahorro
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public realizarRetiro(body: TransaccionAhorroRequestDTO, observe?: 'body', reportProgress?: boolean): Observable<TransaccionAhorroResponseDTO>;
    public realizarRetiro(body: TransaccionAhorroRequestDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TransaccionAhorroResponseDTO>>;
    public realizarRetiro(body: TransaccionAhorroRequestDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TransaccionAhorroResponseDTO>>;
    public realizarRetiro(body: TransaccionAhorroRequestDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling realizarRetiro.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<TransaccionAhorroResponseDTO>('post',`${this.basePath}/api/transacciones-ahorro/retiro`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
